name: imlabtools
channels:
  - defaults
  - conda-forge
  - moble
  - bioconda
dependencies:
  - python=3.9
  - pandas=2.2
  - scipy=1.12
  - numpy=1.26
  - pyliftover=0.4
  - statsmodels=0.14
  - h5py=3.12
  - pyarrow=19.0
  - pip=25.0
  - pip:
    - cyvcf2==0.30.28
    - bgen-reader==4.0.8

